openapi: 3.0.0
info:
  version: 0.0-oas3
  title: Will It Crack
  description: Deep Neural Net for Password Strength Classification
  contact:
    name: Joseph Bellahcen
paths:
  /strength:
    get:
      parameters:
        - in: query
          name: pwd
          required: true
          schema:
            type: string
            description: The user password
      tags:
        - CLASSIFY
      operationId: api.request.rate_pwd
      description: Password classification (weak, medium, strong)
      responses:
        '200':
          description: Password classification (weak, medium, strong)
  /embedding:
    get:
      parameters:
        - in: query     #if it were /embedding/pwd then use in: path
          name: pwd
          required: true
          schema:
            type: string
            description: The user password
      tags:
        - TOKENIZE
      operationId: api.request.tokenize
      description: TF-IDF tokenization of input string
      responses:
        '200':
          description: TF-IDF tokenization of input string
servers:
  - url: 'http://localhost:8080/wic'
