openapi: 3.0.0

info:
  version: 0.0-oas3
  title: Will It Crack
  description: Deep Neural Net for Password Strength Classification
  contact:
    name: Joseph Bellahcen
    
paths:
  /rate-pwd:
    get:
      parameters:
        - in: query
          name: pwd
          required: true
          schema:
            type: string
            description: The user password
            
      tags:
        - CLASSIFY
      operationId: api.request.rate_pwd
      description: Password classification (weak, medium, strong)
      
      responses:
        '200':
          description: Password classified
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Password'
          
  /tokenize-pwd:
    get:
      parameters:
        - in: query
          name: pwd
          required: true
          schema:
            type: string
            description: The user password
            
      tags:
        - TOKENIZE
      operationId: api.request.tokenize
      description: TF-IDF tokenization of input string from corpus
      
      responses:
        '200':
          description: Password tokenized using TF-IDF for corpus
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokenization'

servers:
  - url: 'http://localhost:8080/wic'

components:
  schemas:
    Password:
      description: Password classification (weak, medium, strong)
      type: object
      properties:
        id:
          type: string
          description: Object identifier
        classification:
          type: string
          description: Weak, medium, or strong
          
    Tokenization:
      description: TF-IDF tokenization of input string
      type: object
      properties:
        id:
          type: string
          description: Object identifier
        tokens:
          type: object
          description: Dictionary of token and TF-IDF score pairs
          properties:
            token:
              type: string
            score:
              type: number
