openapi: 3.0.0
info:
  version: 0.0-oas3
  title: Will It Crack
  description: Deep Neural Net for Password Strength Classification
  contact:
    name: Joseph Bellahcen
paths:
  /pwd/<pwd>:
    get:
      tags:
        - CLASSIFY
      operationId: api.request.rate_pwd
      description: Returns cpu information of the hosting server
      responses:
        '200':
          description: Classification of password
servers:
  - url: 'http://localhost:8080/wic'
