openapi: 3.0.0

info:
  version: 0.0-oas3
  title: Will It Crack
  description: Deep Neural Net for Password Strength Classification
  contact:
    name: Joseph Bellahcen
    
paths:
  /strength:
    get:
      parameters:
        - in: query
          name: pwd
          required: true
          schema:
            type: string
            description: The user password
            
      tags:
        - CLASSIFY
      operationId: api.request.rate_pwd
      description: Password classification (weak, medium, strong)
      
      responses:
        '200':
          description: Password succesfully classified
          content:
            text/plain:
              schema:
                description: Password classification (weak, medium, strong)
                type: object
                properties:
                  id:
                    type: string
                    description: Object identifier
                  classification:
                    type: string
                    description: Weak, medium, or strong
          
  /embedding:
    get:
      parameters:
        - in: query
          name: pwd
          required: true
          schema:
            type: string
            description: The user password
            
      tags:
        - TOKENIZE
      operationId: api.request.tokenize
      description: Tokenized using TF-IDF for corpus
      
      responses:
        '200':
          description: TF-IDF tokenization of input string
          content:
            text/plain:
              schema:
                description: TF-IDF tokenization of input string
                type: object
                properties:
                  id:
                    type: string
                    description: Object identifier
                  tokens:
                    type: object
                    description: Dictionary of token and TF-IDF score pairs
                    properties:
                      token:
                        type: string
                      score:
                        type: number

servers:
  - url: 'http://localhost:8080/wic'
